Enumerable methods feature
enelesmai/enumerable-methods pull request #3
Opened 2020-03-18 05:43 UTC by enelesmai

Added custom new methods onto the existing Enumerable module:
* my_each
* my_each_with_index
* my_select
* my_all
* my_any
* my_none
* my_count
* my_map
* my_inject

Added main.rb file
Added my_test.rb file

2020-03-18 13:29 UTC, suretrust requested changes
Hi @enelesmai, 👋 

### Great job, you are definitely up to a great start! 🙌 Please see my comments on your code. 👇 

**Kindly submit another code review request once these issues have been fixed!** _Happy coding!_ 🎉

2020-03-18 13:29 UTC, suretrust commented on .replit
> +  run = "ruby main.rb"
* [x] Files not related to the project should not be committed and added to .gitignore (e.g. `.repit`) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/gitignore.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

2020-03-18 13:29 UTC, suretrust commented on my_enumerable_module.rb
> +  end
* [x] should have working `my_each` identical and returns the same thing as ruby's [`each`](https://ruby-doc.org/core-2.6.4/Array.html#method-i-each). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_each.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))
```ruby
[1,2,3,4,5,6].my_each.class != [1,2,3,4,5,6].each.class
```

2020-03-18 13:29 UTC, suretrust commented on my_enumerable_module.rb
> +    for idx in 0...length
* [x] should have working `my_each_with_index` identical and returns the same thing as ruby's [`each_with_index`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-each_with_index). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_each_with_index.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))
```ruby
[1,2,3,4,5,6].my_each_with_index.class != [1,2,3,4,5,6].each_with_index.class
```

2020-03-18 13:29 UTC, suretrust commented on my_enumerable_module.rb
> +  end
* [x] should have working `my_select` identical and returns the same thing as ruby's [`select`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-select). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_select.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))
```ruby
[1,2,3,4,5,6].my_select.class != [1,2,3,4,5,6].select.class
```

2020-03-18 13:29 UTC, suretrust commented on my_enumerable_module.rb
> +  end
* [ ] should have working `my_all?` identical and returns the same thing as ruby's [`all?`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-all-3F). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_all.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))
```ruby
[1,2,3,4,5,6].my_all?{ |num| num <= 6 } != [1,2,3,4,5,6].all?{ |num| num <= 6 }

[1,2,3,4,5,6].my_all?(Integer) != [1,2,3,4,5,6].all?(Integer)

%w[dog door rod blade].my_all?(/o/) != %w[dog door rod blade].all?(/o/)

[1,2,3,4,5,6].my_all?(3) != [1,2,3,4,5,6].all?(3)
```

2020-03-18 13:29 UTC, suretrust commented on my_enumerable_module.rb
> +  end
* [ ] should have working `my_any?` identical and returns the same thing as ruby's [`any?`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-any-3F). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_any.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))
```ruby
[nil, false, true, []].my_any? != [nil, false, true, []].any?

[1,2,3,4,5,6].my_any?(Integer) != [1,2,3,4,5,6].any?(Integer)

%w[dog door rod blade].my_any?(/d/) != %w[dog door rod blade].any?(/d/)

%w[dog door rod blade].my_any?('cat') != %w[dog door rod blade].any?('cat')
```

2020-03-18 13:29 UTC, suretrust commented on my_enumerable_module.rb
> +  end
* [ ] should have working `my_none?` identical and returns the same thing as ruby's [`none?`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-none-3F). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_none.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))
```ruby
[1,2,3,4,5].my_none?(String) != [1,2,3,4,5].none?(String)

%w[dog door rod blade].my_none?(/z/) != %w[dog door rod blade].none?(/z/)

%w[dog door rod blade].my_none?(5) != %w[dog door rod blade].none?(5)
```

2020-03-18 13:29 UTC, suretrust commented on my_enumerable_module.rb
> +  end
* [ ] should have working `my_count` identical and returns the same thing as ruby's [`count`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-count). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_count.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))
```ruby
[1,2,3,4,5].my_count(3) != [1,2,3,4,5].count(3)
```

2020-03-18 13:29 UTC, suretrust commented on my_enumerable_module.rb
> +  end
* [ ] should have working `my_map` identical and returns the same thing as ruby's [`map`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-map). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_map.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))
```ruby
[1,2,3,4,5,6].my_map.class != [1,2,3,4,5,6].map.class
```

2020-03-18 13:29 UTC, suretrust commented on my_enumerable_module.rb
> +end
* [ ] should have working `my_inject` identical and returns the same thing as ruby's [`inject`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-inject). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_inject.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))
```ruby
[1,2,3,4,5].my_inject(:+) != [1,2,3,4,5].inject(:+)
```

2020-03-19 16:45 UTC, enelesmai commented on my_enumerable_module.rb
> +  end
@suretrust  Do you have any suggestions about this? I Can't find any documentation.

2020-03-19 16:47 UTC, suretrust commented on my_enumerable_module.rb
> +  end
You can use to_enum unless block is given.

2020-03-19 16:54 UTC, enelesmai commented on my_enumerable_module.rb
> +  end
got it! Thanks :)

2020-03-19 23:53 UTC, kobiyoyo requested changes
## Hi @enelesmai    ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, but there are a few more things required. 
- [x] Kindly refer to this doc for guidance https://ruby-doc.org/core-2.6.5/Enumerable.html 
- [x] `my_any?`:
- when no block or argument is given returns true if at least one of the collection is not false or nil
`p [nil, false, nil, false].my_any?` - should return `false`
- when a class is passed as an argument returns true if at least one of the collection is a member of such class
`p ['car'].my_any?(Integer)` should return `false`
- when a Regex is passed as an argument returns false if none of the collection matches the Regex
`p ['ghetto','wild','hellz'].my_any?(/z/)` should return `true`
- when a pattern other than Regex or a Class is given returns false if none of the collection matches the pattern
`p [2,32,].my_any?('cat')` should return `false`
- returns true if the block ever returns a value other than false or nil
`block =  proc { |num| num <= 2 }`
`p [3,43,4,234].my_any?(&block)` should return `false`
- [x] `my_all`  
- when no block or argument is given returns true when none of the collection members are false or nil:
`p [1, true, 'hi', []].my_all?` should return `true`
-  when a Regex is passed as an argument returns true if all of the collection matches the Regex
`p ['d','d','d'].my_all?(/d/)` should return `true`
- [x] `my_inject`:
- When a symbol is specified combines each element of the collection by applying the symbol as a named method
`p (5..10).my_inject(2, :*) - should return 302400`
- Combines all elements of enum by applying a binary operation, specified by a block:
 `p (1..5).my_inject(4) { |prod, n| prod * n }` should return 480
- [x] `my_none?`:
- when a Regex is passed as an argument returns true only if none of the collection matches the Regex
`p ['hello','milk','milo'].my_none?(/i/)` should return `false`
- When no block or argument is given returns true only if none of the collection members is true
`p  [nil, false, nil, false] .my_none?` should return `true`











### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

2020-03-20 22:29 UTC, kobiyoyo requested changes
## Hi @enelesmai    ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, you are almost there, just one more thing  required. 

- [x] `my_none?`:
- When no block or argument is given returns true only if none of the collection members is true
`p [nil, false, nil, true] .my_none?` should return `false`










### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

2020-03-21 15:34 UTC, shshamim63 commented
## Status :tada:  Approved :tada: 
___
Hi @enelesmai :wave: , 
Awesome job :clap: . You have covered all the changes asked by the previous reviewers. The code looks neat and clean. But just found an issue, but as it was not mentioned previously by the previous reviewers, gonna mark it as optional. But believe me, adding some line of codes gonna make it perfect. 
___
### :clubs: Optional Changes :clubs: 
___
- `multiply_els` that uses `my_inject` as described on Odin ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/multiply_els.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))
You forgot to add it to your source code. just add the lines after your module end. Cause multiply _els is not an enumerable method.
```ruby
def multiply_els(arr)
  p arr.my_inject(:*)
  p arr.my_inject { |memo, n| memo * n }
end
```
- Congrats you have added your sort of test cases. But believe me, this is not the way to write tests. You will add the actual test by using RSpec. So leaving those test cases now gonna be redundant. So, I will suggest you get rid of them now.
___
#### This :+1: is from me. You can go-ahead.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain
[Linkedin](https://www.linkedin.com/in/shakhawathossainshamim/) | [Twitter](https://twitter.com/Shshamim090)

2020-03-21 22:59 UTC, enelesmai commented
Hello, @shshamim63 I already did what you suggested, thank you for that! And I have a question now, should I push this to the develop branch?

2020-03-21 23:03 UTC, merged